title: Where's My Documentation?
short_title: WMD
description: "A simple blog to showcase my various projects"
#url: "https://blog.lackshan.dev"
url: ""
github_username:  Lackshan
language: en_US
paginate: 10
paginate_path: "/page/:num/"
permalink: none
markdown: kramdown
future: true

plugins:
  - jekyll-paginate